### ISSUE TITLE
Issue connecting Snapcast

### ISSUE THREAD

**Issue by acidrs03** [spiro-c/LedFxDocker-Virtual#11]
Hello I have Mopidy and Snapcast running in docker and wanted to get this LedFx container setup to work with them but am having a couple of issues.

My Mopidy has an audio output that is
output = audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! filesink location=/tmp/snapfifo

From what i can tell this LedFx container is looking for an output in a file called stream. So if i change the Mopidy out to
output = audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S32LE ! filesink location=/tmp/stream

LedFx can access that, however that then renders my snapcast unavailable as it is wanting snapfifo.

So my question is how would i get this all working together, what files do i need to edit to have this all work in sync. If this is a mopidy config file setting, and someone has an example i can look at that would be great. I'm just a little confused at how this all works together.

**Comment by spiro-c** [comment]
You dont need to edit any file just pass the ip address of your snapcastserver like `environment` variable to the container and the container will connect to the running snapcastserver reading from the fifo file is other option you can use to get the audio for the container so this simple docker-compose.yml need to work
```yml
version: '3'

services:
  ledfx-virt:
    image: spirocekano/ledfx-virt:beta
    container_name: ledfx-virt
    hostname: ledfx-virt
    environment: 
      - HOST=192.168.xxx.yyy
    ports:
      - 8888:8888
    volumes:
      - ./ledfx-config:/root/.ledfx
      ```
